# Generated by Django 2.1.7 on 2019-11-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='replied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day_of_appointment',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='asked_On',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
