# Generated by Django 2.1.7 on 2019-11-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_auto_20191127_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
