# Generated by Django 2.1.7 on 2019-11-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_query_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointed',
            field=models.BooleanField(default=False),
        ),
    ]
