# Generated by Django 2.1.7 on 2019-12-07 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_auto_20191207_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day_of_appointment',
            field=models.DateTimeField(blank=True),
        ),
    ]
