# Generated by Django 2.1.7 on 2019-12-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_auto_20191207_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='requested_on',
        ),
    ]
