# Generated by Django 2.1.7 on 2019-12-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_remove_appointment_requested_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
