# Generated by Django 2.1.7 on 2019-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0010_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day_of_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
