# Generated by Django 2.1.7 on 2019-12-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_auto_20191207_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
