# Generated by Django 2.1.7 on 2019-12-08 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0012_query_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='replied_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
