# Generated by Django 2.1.7 on 2019-12-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0014_auto_20191208_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
