# Generated by Django 2.1.7 on 2019-12-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0015_query_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='reason',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
